spring:
  datasource:
    #url: jdbc:h2:mem:mydb
    url: jdbc:h2:file:./data/jobmanager
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    #show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      settings:
        web-allow-others: true
      path: /h2-console
      enabled: true
server:
  servlet:
    context-path: /api
logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
#            RestTemplate: INFO